version: '3.7'

services:
  frontend:
    build: ./front-end/pagina_react
    #image: sergiobarpor/frontend:lastest
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    restart: always
    build: ./back_end/bd
    #image: sergiobarpor/backend:lastest
    ports:
      - "4000:4000"
    depends_on:
      - database

  database:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'my_database'
      MYSQL_USER: 'my_user'
      MYSQL_PASSWORD: 'my_password'
      MYSQL_ROOT_PASSWORD: 'root_password'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - "3306:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
