version: '3'
services:
  frontend:
    build:
      context: ./front-end/pagina-de-inicio
    ports:
      - "80:80"
    depends_on:
      - backend
  backend:
    build:
      context: ./back-end/bd
    ports:
      - "3000:3000"
    depends_on:
      - database
    volumes:
      - ./back-end:/app/bd
  database:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
      - ./db/prueba.sql:/docker-entrypoint-initdb.d/prueba.sql

    

