apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  database: bXlfZGF0YWJhc2U= # Base64 encoded 'my_database'
  user: bXlfdXNlcg==        # Base64 encoded 'my_user'
  password: bXlfcGFzc3dvcmQ= # Base64 encoded 'my_password'
  root_password: cm9vdF9wYXNzd29yZA== # Base64 encoded 'root_password'
