apiVersion: apps/v1
kind: Deployment
metadata:
  name: mi-aplicacion
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mi-aplicacion
  template:
    metadata:
      labels:
        app: mi-aplicacion
    spec:
      containers:
      - name: frontend
        image: sergiobarpor/frontend:lastest
        ports:
        - containerPort: 3000
      - name: backend
        image: sergiobarpor/backend:lastest
        ports:
        - containerPort: 4000

---
apiVersion: v1
kind: Service
metadata:
  name: mi-aplicacion-service
spec:
  selector:
    app: mi-aplicacion
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000


#---
#apiVersion: apps/v1
#kind: StatefulSet
#metadata:
#  name: mi-base-de-datos
#spec:
  # replicas: 1
  # serviceName: mi-base-de-datos
  # selector:
  #   matchLabels:
  #     app: mi-base-de-datos
  # template:
  #   metadata:
  #     labels:
  #       app: mi-base-de-datos
  #   spec:
  #     containers:
  #     - name: postgres
  #       image: postgres:latest
  #       ports:
  #       - containerPort: 5432
  #       env:
  #       - name: POSTGRES_PASSWORD
  #         value: tu_contraseña_secreta
